/*
 *  UCF COP3330 Fall 2021 Assignment 4 Solutions
 *  Copyright 2021 Srignan Paruchuru
 */


@startuml

class Solution41
{
-names: ArrayList<String>
-count: int
+main()
+obj = Read() object
+w = Write() object

}
class Read
{
+getnames()
+getcount()
}
class Write
{
+write_to_file()
}

Solution41 "get names and count from Read()" --- Read
Solution41 "use Write() to create output file"--- Write
@enduml