@startuml
'https://plantuml.com/sequence-diagram

class App{
}

class ReplaceWord{
    - Path fileName
    + getFile void()
    + replace String()
}

class CreateFile{
    - Scanner in
    + askFilePath String()
    + writeOut void(String fileText)
}


App o-> ReplaceWord
@enduml